[package]
name = "once"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8.15"
structopt = { version = "0.3", default-features = false }
dirs = "5.0.1"
log = "0.4.22"
env_logger = "0.11.5"